### ISSUE TITLE
Your code is not runnable.

### ISSUE THREAD

**Issue by yingqichao** [basilevh/dissecting-image-crops#1]
Just what kind of images are qualified as "high-quality"?

Error:

File "/home/qichaoying/Downloads/dissecting-image-crops-main/data.py", line 555, in __getitem__
    raise RuntimeError('Could not load a suitable input image after 32 tries.')
RuntimeError: Could not load a suitable input image after 32 tries.

I have tried MS-COCO(jpg) and CelebA(png) as training set.

**Comment by basilevh** [comment]
The most likely reason is insufficiently high resolution. The method is designed for spatially large images only, because patches would start overlapping otherwise. Check the data loader code for more details regarding size. Does switching dataset help?

**Comment by yingqichao** [comment]
Thanks for your reply. I find the minimum required image size is 768*768, otherwise the patch-wise detector cannot work.
